[build-system]
requires = ["setuptools>=61.0", "cffi>=1.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ransac-line"
version = "0.1.0"
dependencies = ["cffi>=1.0.0"]

[tool.setuptools]
packages = ["ransac_line"]
